version: '3'

services:
  mongo:
    image: mongo:3.6.3
    container_name: mongo
    env_file:
      - server/.env
    volumes:
      - ./db/data:/data/db
      - ./db/db-init/:/docker-entrypoint-initdb.d/
      - ./db/restore:/restore
    networks:
      - vas_web
    ports:
      - 27016:27017
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 3001:80
    volumes:
      - ./nginx/default.conf:/tmp/default.template
      - ./client/build:/var/www/html:rw,cached
    restart: always
    entrypoint: /bin/bash -c 'cat /tmp/default.template | sed "s/\\\$$domain/localhostdocke/g" > /etc/nginx/conf.d/default.conf && nginx -g "daemon off;"'
    networks:
      - vas_web
    links:
      - mongo
  api:
    image: node:12.18.4
    container_name: api
    working_dir: /home/node/app
    volumes:
      - ./server:/home/node/app
      - ./db/restore:/home/node/db
    networks:
      - vas_web
    command: "sh -c \"npm install && npm run dev\""
    depends_on:
      - mongo
volumes:
  db:
    driver: local
networks:
  vas_web:
    driver: bridge
