version: '3'

services:
  db:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    env_file:
      - server/.env
    volumes:
      - db:/data/dbc
      - ./db-init:/docker-entrypoint-initdb.d/
    networks:
      - web
    ports:
      - 27017:27017
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 3000:80
      - 8081:8081
    volumes:
      - ./nginx/default.conf:/tmp/default.template
      - ./client/build:/var/www/html:rw,cached
    restart: always
    entrypoint: /bin/bash -c 'cat /tmp/default.template | sed "s/\\\$$domain/localhostdocke/g" > /etc/nginx/conf.d/default.conf && nginx -g "daemon off;"'
    networks:
      - web
volumes:
  db:
    driver: local
networks:
  web:
    driver: bridge
