name: deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Adding checkout action
        uses: actions/checkout@v2
      - name: Use Node.js 12.18.4
        uses: actions/setup-node@v1
        with:
          node-version: 12.18.4
      - name: Building app
        uses: appleboy/ssh-action@e59c0ee97a7e5240ed9eb489791adbb9c9ac7f6b
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{secrets.SSH_PRIVATE_KEY}}
          port: ${{secrets.PORT}}
          script: |
            git clone https://github.com/FIU-VAS/VAS || (cd VAS ; git pull)
            cd ./server
            touch .env
            echo "MONGODB_USERNAME=${{ secrets.MONGODB_USERNAME }}" > .env
            echo "MONGODB_PASSWORD=${{ secrets.MONGODB_PASSWORD }}" >> .env
            echo "MONGODB_URL=${{ secrets.MONGODB_URL }}" >> .env
            echo "MONGODB_TABLE_NAME=${{ secrets.MONGODB_TABLE_NAME }}" >> .env
            echo "SMTP_HOST=${{ secrets.SMTP_HOST }}" >> .env
            echo "SMTP_PORT=${{ secrets.SMTP_PORT }}" >> .env
            echo "SMTP_SECURE=${{ secrets.SMTP_SECURE }}" >> ./server/.env
            echo "MONGO_INITDB_ROOT_USERNAME=${{ secrets.MONGO_INITDB_ROOT_USERNAME }}" >> .env
            echo "MONGO_INITDB_ROOT_PASSWORD=${{ secrets.MONGO_INITDB_ROOT_PASSWORD }}" >> .env
            echo "MONGO_INITDB_DATABASE=${{ secrets.MONGO_INITDB_DATABASE }}" >> .env
            echo "PROJECT_DIRECTORY=${{ secrets.PROJECT_DIRECTORY }}" >> .env
            echo "HOST_USER=${{ secrets.HOST_USER }}" >> .env
            npm install
            pm2 restart ecosystem.config.js --env production

            cd ../client
            npm install
            npm run build
            mv -r ./build ~/vasclient
      - name: Install PM2
        run: cd ./server && npm i pm2 -g

      - name: Prepare deployment
        run: cd ./server && env $(cat .env | grep -v \"#\" | xargs) pm2 deploy production setup
      - name: Deploy
        run: cd ./server && env $(cat .env | grep -v \"#\" | xargs) pm2 deploy ecosystem.config.js production